version: '3'

services:
  password_generator:
    build:
      dockerfile: Dockerfile
    command: python config/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
